version: '3.1'
services:
  mysql:
    image: mysql:5.7.22
    environment:
      MYSQL_DATABASE: arca
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
    expose:
      - '3306'
    ports:
      - '3306:3306'